#!/usr/bin/env bash
# This script installs specified versions of .NET Core and the latest LTS

# Function to install a specific .NET Core version
install_dotnet_version() {
    local version="$1"
    echo "Installing .NET Core version $version..."
    curl --silent --show-error --location https://dot.net/v1/dotnet-install.sh \
        | sudo bash /dev/stdin -c "$version" --install-dir /usr/share/dotnet
}

# Install .NET Core versions
install_dotnet_version LTS
install_dotnet_version 6.0
install_dotnet_version 7.0
install_dotnet_version 8.0

# Create a symlink to dotnet executable, if not present
if [ ! -f /usr/bin/dotnet ]; then
    sudo ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet
fi

