#!/usr/bin/bash 

work_dirs=(
"git@github.com:dv8team/SRPDV8.git;Srpdv8" 
"git@github.com:dv8team/DV8.Identity.Server.git;IdentityServer" 
"git@github.com:dv8team/MobileApp-managed-.git;MobileApp"
"git@github.com:dv8team/DV8webapi.git;MobileApi"
"git@github.com:dv8team/WellDesign.git;WellDesign"
"git@github.com:dv8team/website.git;Website"
)
read -p "Install dv8 repos? (y/n)" work
if [ "$work" == "y" ]; then
	if [ ! -d "$HOME/work" ]; then
		mkdir "$HOME/work"
	fi
	echo "Installing dv8 repos to $HOME/work..."
	for i in ${work_dirs[@]}; do
		repo=$(echo $i | cut -f1 -d';')
		dest=$(echo $i | cut -f2 -d';')
		git clone $repo "$HOME/work/$dest"
	done
else 
	echo "skipping dv8 repos"
fi
 
read -p "Install personal repos? (y/n)" personal
if [ "$personal" == "y" ]; then
	if [ ! -d "$HOME/personal" ]; then
		mkdir "$HOME/personal"
	fi
	echo "no personal repos to install"
else 
	echo "skipping personal repos"
fi
