#!/usr/bin/bash

echo "[Setup script] generating new ed25519 ssh key"

loop=true
while $loop
do
	read -p "Enter your email: " email
	read -p "Is $email correct (y/n)?" conf
	case "$conf" in 
		y|Y) loop=false;;
		* ) echo "invalid response";;
	esac
done

ssh-keygen -t ed25519 -C "$email"

loop=true
while $loop
do
	read -p "Ensure you have added the .pub ssh key to github. Then type 'continue' to continue: " choice
	case "$choice" in 
	  'continue' ) loop=false;;
	  * ) echo "invalid response";;
	esac
done
